* History of Programming Languages

Catalog of programming languages and their history.

The history of building programming languages is preceeded by works in algebra, mathematical logic, and constructivism.

* Prior Art
* Syllogisms and ancient/medieval computation devices.
* Emergence of Algebraic language
* Marriage of logic and algebra
* Peirce/Frege revolution
* Logic of relatives
* Constructivism vs. Formalism
* Logicism
* Schönfinkel operators
* Gödel numbering
Gödel’s work can in essence be thought of as having a programming language. This is taken up by Chaitin in his book on algorithmic complexity.
* Emergence of computational formalisms

Curry/Schönfinkel, Russell/Post, Church, Gödel, Turing, Von Neumann/McCullough Pitts

* Category theory

* Plankälkul

* FORTRAN

* LISP

* ALGOL

* Peter Landin

* Emacs Lisp

* LCF

* Scheme

** Scheme 311

Ancestory of MacScheme. First version written by Will Clinger.

* Chicken Scheme

* ML

* COBOL

* PASCAL

* C

* Forth

* Erlang

* PL/I

* Ada

* Factor

* C++

* Coq

* Befunge

* Java

* Go

* Inform

* Piet

* Javascript

* Clojure

* Elixir

* Jot

* Iota

* LASP

* Elm
